CMake+Android: Skip tests with SetCameraMode
src/core.c does explicitly skip including <camera.h> on Android
and tests fail. Therefore skip these failing tests.

Closes #507.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -86,7 +86,9 @@ script:
   - if [ "$GLFW" != "SYSTEM" ]; then make package; fi;
   - sudo make install
   - pkg-config --static --libs raylib
-  - nm -g release/libraylib.a | grep glfwGetProcAddress || (echo "libraylib.a doesn't contain GLFW symbols! Aborting..." && false)
+  - if [[ "$ARCH" != *-android ]]; then
+      nm -g release/libraylib.a | grep glfwGetProcAddress || (echo "libraylib.a doesn't contain GLFW symbols! Aborting..." && false);
+    fi
 
 deploy:
   provider: releases
